[versions]
agp = "8.2.2"
kotlin = "1.9.22"
hilt = "2.48"
ksp = "1.9.22-1.0.16"
room = "2.6.2"
compose = "1.5.8"
material3 = "1.2.0"
coroutines = "1.7.3"
coil = "2.4.0"
tflite = "2.12.0"
androidx-security = "1.1.0-alpha04"
work = "2.8.1"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"

androidx-compose-ui = "androidx.compose.ui:ui:${compose}"
androidx-compose-ui-graphics = "androidx.compose.ui:ui-graphics:${compose}"
androidx-compose-ui-tooling-preview = "androidx.compose.ui:ui-tooling-preview:${compose}"
androidx-material3 = "androidx.compose.material3:material3:${material3}"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.2"

hilt-android = "com.google.dagger:hilt-android:${hilt}"
hilt-compiler = "com.google.dagger:hilt-compiler:${hilt}"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.1.0-alpha01"

room-runtime = "androidx.room:room-runtime:${room}"
room-ktx = "androidx.room:room-ktx:${room}"
room-compiler = "androidx.room:room-compiler:${room}"

coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${coroutines}"

coil-compose = "io.coil-kt:coil-compose:${coil}"

tensorflow-lite = "org.tensorflow:tensorflow-lite:${tflite}"
tensorflow-lite-support = "org.tensorflow:tensorflow-lite-support:${tflite}"
tensorflow-lite-gpu = "org.tensorflow:tensorflow-lite-gpu:${tflite}"

androidx-security-crypto = "androidx.security:security-crypto:${androidx-security}"

work-runtime-ktx = "androidx.work:work-runtime-ktx:${work}"

junit = "junit:junit:${junit}"
androidx-junit = "androidx.test.ext:junit:${androidx-junit}"
espresso-core = "androidx.test.espresso:espresso-core:${espresso-core}"
androidx-compose-ui-test-junit4 = "androidx.compose.ui:ui-test-junit4:${compose}"
androidx-compose-ui-tooling = "androidx.compose.ui:ui-tooling:${compose}"
androidx-compose-ui-test-manifest = "androidx.compose.ui:ui-test-manifest:${compose}"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }